name: "Build and Deploy"

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install Jekyll and Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install npm Dependencies
        run: npm ci

      - name: Install Bootstrap and Copy to Assets
        run: |
          npm install bootstrap
          mkdir -p assets/css/vendors
          cp -r node_modules/bootstrap/scss assets/css/vendors/bootstrap

      - name: Build Jekyll Site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: "production"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: "_site"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: 2
